32bit: false
memory: "2048"
npmmirror: "https://registry.npmjs.org/"
owner: "Bot Wrangler <bw@example.com>"
name: "Hubot"
description: "Delightfully aware robutt"
adapter: "shell"
use_sources_list: false
